[global]
shuffle = false

[[batch]]
prompt = "informatics/database.txt"
n_problems = 24
handler = "multiple_choice/default"

[[batch]]
prompt = "informatics/database_true_false.txt"
n_problems = 4
handler = "true_false/default"
