[global]
shuffle = false
back_handler = "default"

[[batch]]
prompt = "informatics/database"
n_problems = 24
front_handler = "multiple_choice/default"

[[batch]]
prompt = "informatics/database"
n_problems = 4
front_handler = "true_false/default"
